version: '3.9'

services:
  db:
    image: postgresql
    restart: always
    container_name: prisma-test
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: coupon
